---  # Update remote systems
- hosts: all
  connection: ssh
  become: yes
  become_method: sudo
  tasks:
    - name: Update remote system
      yum:
        name: "*"
        state: latest

    - name: Reboot remote systems
      command: reboot
